### ISSUE TITLE
使用在ListView中时，有残影

### ISSUE THREAD

**Issue by chentao7v** [sfsheng0322/MarqueeView#12]
在ListView中作为一个Item，来回快速滑动
，当MarqueeView切换到下一条时，就会出现残影

![1](https://cloud.githubusercontent.com/assets/17487668/21085858/9bba56a4-c051-11e6-8b49-254cf15636fc.png)

**Comment by sfsheng0322** [comment]
重影问题可参考以下解决方案

@Override
public void onStart() {
    super.onStart(); 
    marqueeView.startFlipping();
}

@Override
public void onStop() {
    super.onStop();
    marqueeView.stopFlipping();
}
