### ISSUE TITLE
重叠字

### ISSUE THREAD

**Issue by githubityu** [sfsheng0322/MarqueeView#13]
fragment来回切换的时候会经常出现重叠字

**Comment by sfsheng0322** [comment]
重影问题可参考以下解决方案

@Override
public void onStart() {
    super.onStart(); 
    marqueeView.startFlipping();
}

@Override
public void onStop() {
    super.onStop();
    marqueeView.stopFlipping();
}

**Comment by shengguan** [comment]
@Override
    public void onHiddenChanged(boolean hidden) {
        super.onHiddenChanged(hidden);
        if (hidden){
            marqueeView.stopFlipping();
        }else{
            marqueeView.startFlipping();
        }
    }

可以试一下这个
