### ISSUE TITLE
getWidth()获取的宽度为0，怎么破啊

### ISSUE THREAD

**Issue by syb0327** [sfsheng0322/MarqueeView#15]

**Comment by sfsheng0322** [comment]
你可以添加getViewTreeObserver().addOnGlobalLayoutListener

**Comment by sfsheng0322** [comment]
或者View.post

**Comment by sfsheng0322** [comment]
你可以添加: getViewTreeObserver().addOnGlobalLayoutListener 或者通过 View.post 方式试试
