### ISSUE TITLE
创建的对象太多,能否销毁已经滚出屏幕的对象

### ISSUE THREAD

**Issue by hjmJhon** [sfsheng0322/MarqueeView#22]
非常感谢让我了解到了跑马灯的这种实现方式.但是对于这种方式,我有个疑虑就是,如果集合数据很多,那么就会创建很多的TextView.所以能不能再每个动画结束时将对应的TextView置为null,便于回收,减少内存开销.

**Comment by sfsheng0322** [comment]
这个问题解决了，谢谢你的建议，其实创建三个textView就可以了，我的做法是复用已经创建好的那三个TextView，请更新到 V1.3版本就可以了。
