### ISSUE TITLE
关于重复创建对象问题startWithList(List<? extends CharSequence> notices) 

### ISSUE THREAD

**Issue by HPLY** [sfsheng0322/MarqueeView#27]
for(final int i = 0; i < this.notices.size(); ++i) {
                final TextView textView = this.createTextView((CharSequence)this.notices.get(i), i);
                textView.setOnClickListener(new OnClickListener() {
                    public void onClick(View v) {
                        if(MarqueeView.this.onItemClickListener != null) {
                            MarqueeView.this.onItemClickListener.onItemClick(i, textView);
                        }

                    }
                });
                this.addView(textView);
            }

假如，list数据是后端返回的，可能是一些简短的鸡汤文，上千上万条，解析之后list的size可能很大，这里创建TextView的方式比较简单粗暴，直接循环，new TextView会不会有问题呢

**Comment by sfsheng0322** [comment]
已经解决啦，其实创建三个TextView就可以啦，复用创建好的，谢谢你哈
