### ISSUE TITLE
fragment中使用重影，以下设置没效果

### ISSUE THREAD

**Issue by xiaobaoCat** [sfsheng0322/MarqueeView#28]
@Override
    public void onStart() {
        super.onStart();
        tvMessage.startFlipping();
    }
    @Override
    public void onStop() {
        super.onStop();
        tvMessage.stopFlipping();
    }

**Comment by xiaobaoCat** [comment]
FragmentTabHost切换的时候

**Comment by ericacx** [comment]
这个你解决了吗？我这样设置也是，每次切换到这个页面的时候，会出现一瞬间的重影，然后就正常了。这是什么情况？

**Comment by sfsheng0322** [comment]
欢迎在V1.3.0上测试哈
