### ISSUE TITLE
在activity里面使用的 问题

### ISSUE THREAD

**Issue by qq171161636** [sfsheng0322/MarqueeView#33]
老哥,我copy你的代码的.然后一进入页面   第一条条目会先闪一下   然后再从第一条到最后一条重复滚动

**Comment by r17171709** [comment]
遇到相同的问题了

**Comment by coding404** [comment]
我也遇到了，将adapter中的list做初始化就解决了，private List<T> mList=new ArryList<T>();这样就行了

**Comment by qq171161636** [comment]
你是说在activity里吧初始化放在oncreate方法之前?

**Comment by coding404** [comment]
不是，MarqueeView 中第50行代码： private List<? extends CharSequence> notices = new ArrayList<>();
你在做自定义的时候这句话没有初始化。

**Comment by sfsheng0322** [comment]
我用的没问题呢，好囧，还有问题请联系我哈，微信：sfs321

**Comment by GitHubforcjh** [comment]
我也遇到了这样的问题,请问你们怎么解决的

**Comment by xiaomaothm** [comment]
我也遇到了

**Comment by LinkSy** [comment]
怎么解决呢

**Comment by logney** [comment]
同样问题

**Comment by sfsheng0322** [comment]
找到原因了，V1.3.3 解决这个问题了。
