### ISSUE TITLE
数据为1条时，直接崩溃，改一下  if (notices.size() >= 1) 就OK了

### ISSUE THREAD

**Issue by 852172891** [sfsheng0322/MarqueeView#34]
if (notices.size() > 1) {  换成  if (notices.size() >= 1) { 就OK了

private boolean start(@AnimRes int inAnimResId, @AnimRes int outAnimResID) {
        removeAllViews();
        clearAnimation();

        position = 0;
        addView(createTextView(notices.get(position)));

        if (notices.size() > 1) {
            setInAndOutAnimation(inAnimResId, outAnimResID);
            startFlipping();
        }

**Comment by sfsheng0322** [comment]
还是判断 animation 是否 null 吧

**Comment by nb312** [comment]
要改变里面的东西吗
