### ISSUE TITLE
ullPointerException: Attempt to invoke virtual method 'void android.view.animation.Animation.setAnimationListener

### ISSUE THREAD

**Issue by alex2390** [sfsheng0322/MarqueeView#40]
当 List<String> info = new ArrayList<>();
        info.add("大家好，我是孙福生");
        marqueeView.startWithList(info);
info只有一条数据时报空指针。。

当String notice = "心中有阳光，脚底有力量！";
        marqueeView.startWithText(notice);
notice长度太短时也报空指针

 getInAnimation()为null

**Comment by sfsheng0322** [comment]
try v1.3.2
