### ISSUE TITLE
第一次显示的时候效果有问题 

### ISSUE THREAD

**Issue by 757027949** [sfsheng0322/MarqueeView#43]
初次的第一条数据开始动画的时候直接隐藏 过渡不对 是不是有问题？

**Comment by sfsheng0322** [comment]
你试试v1.3.3

**Comment by qianshengta** [comment]
解决了吗？我用的也是1.3.3，同样的问题
        <com.sunfusheng.marqueeview.MarqueeView
            android:id="@+id/main_tv_headline"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_margin="5dp"
            android:layout_weight="1"
            android:ellipsize="end"
            android:maxLines="1"
            app:mvAnimDuration="1000"
            app:mvDirection="bottom_to_top"
            app:mvGravity="left"
            app:mvInterval="3000"
            app:mvSingleLine="true"
            app:mvTextColor="@color/colorBlue"
            app:mvTextSize="@dimen/text_size_H6"/>

          if (!ListUtils.isEmpty(mainInfo.getNewsList())) {
                newsLists = mainInfo.getNewsList();
                List<String> list = new ArrayList<>();
                for (NewsList newsList : mainInfo.getNewsList()) {
                    list.add(newsList.getTitleOne());
                }
                mainTvHeadline.startWithList(list);
            }

**Comment by 757027949** [comment]
木有 就是现在的第一个问题情况
