### ISSUE TITLE
marqueeView.startFlipping();这个方法写到onStart方法， 进到界面后会第一条先不动，然后下面又出来第一条开始轮播， 而且点击item跳转后再返回，轮播就停止了， 但是当写到onResume方法时,又会出现第一种情况

### ISSUE THREAD

**Issue by mwj1103** [sfsheng0322/MarqueeView#46]

**Comment by mwj1103** [comment]
暂时这么处理的  加入数据后开始的 marqueeView.startFlipping()，onPause()之后执行的marqueeView.stopFlipping();然后在onResume()方法中调用了加入数据的方法

**Comment by birdfly2014** [comment]
我也碰到这个问题，而且我的滚动是在recyclerview中中的item中。  请问如何解决。

**Comment by sfsheng0322** [comment]
找到原因了，V1.3.3 解决这个问题了。
