### ISSUE TITLE
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

### ISSUE THREAD

**Issue by C-isCoder** [sfsheng0322/MarqueeView#5]
集成的时候出装错了，貌似是跟属性冲突？
E:\C_Workspace\PointHelp\app\build\intermediates\res\merged\debug\values-v23\values-v23.xml

Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

Error:(33) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

 compileSdkVersion 22
    buildToolsVersion "22.0.1"
 minSdkVersion 19
        targetSdkVersion 22

**Comment by C-isCoder** [comment]
解决了：下载源码把 targetSdkVersion  compileSdkVersion 版本改成我项目的版本就好了。估计源码那个23太高了。

**Comment by sfsheng0322** [comment]
那还是你的项目版本太低喽
