### ISSUE TITLE
'void com.sunfusheng.marqueeview.MarqueeView.startWithList(java.util.List)' on a null object reference

### ISSUE THREAD

**Issue by laonayan** [sfsheng0322/MarqueeView#68]
`        
        //跑马灯
        mMarqueeView = (MarqueeView) 
        getView().findViewById(R.id.marqueeView);mMarqueeView.startWithList(tips);
        mMarqueeView.startWithList(tips, R.anim.anim_bottom_in, R.anim.anim_top_out);`

**Comment by sunfusheng** [comment]
运行我的demo有问题吗？
