### ISSUE TITLE
能支持多条吗

### ISSUE THREAD

**Issue by zhaoxiuyu** [sfsheng0322/MarqueeView#7]
这个只能显示一条数据，能支持多条跑马灯吗，类似于这种
![1t v3qsj 9 2 8 u f ky](https://cloud.githubusercontent.com/assets/16554580/19379956/6047ca6e-9227-11e6-936d-8e953e5ee954.png)

**Comment by sfsheng0322** [comment]
可以啊

**Comment by troyccc** [comment]
哪个属性设置几条滚动呀

**Comment by troyccc** [comment]
> 可以啊
哪个属性设置几条滚动呀
